version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    command: >
      bash -c "bundle install &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0.25
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
volumes:
  db_data:
